server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active: git
  cloud:
    config:
      server:
        native:
          search-locations: file://${user.dir}/..config
        git:
          uri: file://./config
#          uri: file://${user.dir}/../config
#          uri: https://github.com/nooose/spring-cloud
          default-label: master
          # private repository
#          username:
#          password:
